# Generated by Django 2.1.1 on 2018-09-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='toice',
            new_name='topic',
        ),
    ]
